In [1]:
import numpy as np

In [5]:
print(np.__version__)

1.19.5


In [12]:
vectorNull = np.tile(None, 8)
vectorNull

array([None, None, None, None, None, None, None, None], dtype=object)

In [13]:
vectorNull[3] = 1
vectorNull

array([None, None, None, 1, None, None, None, None], dtype=object)

In [17]:
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [113]:
m33 = np.arange(9).reshape(3,3)
m33

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
mIdentity = np.identity(3)
mIdentity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
mRandom = np.random.rand(3,3,3)
mRandom

array([[[0.90654301, 0.70561737, 0.69212309],
        [0.72995701, 0.52731645, 0.33065741],
        [0.67279861, 0.28986303, 0.57802084]],

       [[0.00201846, 0.90350062, 0.95485804],
        [0.99283026, 0.08451748, 0.25504748],
        [0.40260876, 0.80794464, 0.87444744]],

       [[0.06050848, 0.24835671, 0.95918652],
        [0.57850841, 0.40040551, 0.26422588],
        [0.77531973, 0.49734735, 0.75418034]]])

In [32]:
mRandom10 = np.random.rand(10,10)
mRandom10.min(), mRandom10.max()

(0.01083736415335923, 0.9858738046989332)

In [44]:
test = np.diag([1,2,3,4],-1)
test

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [47]:
ar = np.random.rand(5)
sum(ar), ar.mean()

(2.1629765261726384, 0.43259530523452766)

In [59]:
l = [x for x in range(11)]
l, len(l)

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 11)

In [61]:
random10 = np.random.rand(10)
random10

array([0.13970766, 0.58710453, 0.03214917, 0.2439067 , 0.64140842,
       0.14118874, 0.39869798, 0.85394234, 0.90200767, 0.61472853])

In [117]:
A = np.array([1,2,3,4,5])
B = np.array([1,2,3,4,6])
np.array_equal(A,B)

False

In [68]:
a = np.array([0,1,0,5,2,1,4,5,2], dtype=("float32"))
a

array([0., 1., 0., 5., 2., 1., 4., 5., 2.], dtype=float32)

In [71]:
a.dtype = "int32"
a

array([         0, 1065353216,          0, 1084227584, 1073741824,
       1065353216, 1082130432, 1084227584, 1073741824], dtype=int32)

In [86]:
mat55 = np.random.randint(10, size=(5, 5))
moy = mat55.mean()
eType = mat55.std()
mat55 = (mat55-moy)/eType
mat55

array([[ 0.85291032, -1.51628501,  0.51445384, -0.16245911, -1.17782854],
       [-0.50091558,  0.85291032,  1.52982327,  0.17599737,  0.51445384],
       [ 0.51445384, -1.51628501,  0.51445384, -1.17782854, -1.17782854],
       [ 1.52982327,  0.85291032,  1.52982327, -1.51628501, -0.83937206],
       [-0.83937206,  1.19136679, -0.50091558, -0.16245911,  0.51445384]])

In [93]:
mat22 = np.random.randint(10, size=(2,2))
print(mat22)
print(mat22.transpose())

[[1 0]
 [5 0]]
[[1 5]
 [0 0]]


In [108]:
def changeRandomElem(matrice):
    form = matrice.shape
    x = np.random.randint(form[0])
    y = np.random.randint(form[1])
    matrice[x][y] = np.random.randint(0,50)
    
    return ((x,y), matrice)
mat = np.random.randint(10, size=(5, 5))
print(mat)
print(changeRandomElem(mat))

[[8 4 3 4 3]
 [4 7 2 5 5]
 [7 4 2 3 5]
 [3 7 0 0 8]
 [1 4 7 6 6]]
((0, 2), array([[ 8,  4, 30,  4,  3],
       [ 4,  7,  2,  5,  5],
       [ 7,  4,  2,  3,  5],
       [ 3,  7,  0,  0,  8],
       [ 1,  4,  7,  6,  6]]))


In [112]:
mat553 = np.random.randint(10, size=(5, 5, 3))
mat55 = np.random.randint(10, size=(5, 5))
np.matmul(mat553, mat55)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 3)