In [15]:
!python3 -m pip install numpy  # specifically Python 3.4

  Using cached https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl


In [24]:
!python3 -m pip list | grep numpy

DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
numpy (1.19.5)


In [25]:
import numpy as np

In [29]:
ar = np.array([1,2,3], dtype="int8")
ar

array([1, 2, 3], dtype=int8)

In [30]:
ar.min()

1

In [31]:
ar.max()

3

In [32]:
ar.mean()

2.0

In [33]:
ar.std()

0.816496580927726

In [36]:
ar.dtype

dtype('int8')

In [37]:
m = np.array([[1,2], [3,4]])
m

array([[1, 2],
       [3, 4]])

In [38]:
m[0][1]

2

In [40]:
m.shape

(2, 2)

In [41]:
m2 = np.array([1,2,3,4,5], ndmin=2 )
m2

array([[1, 2, 3, 4, 5]])

In [44]:
m2.shape = (5,1)
m2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [45]:
m2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [46]:
b= np.linspace(0,2,4)
b

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [47]:
b**2


array([0.        , 0.44444444, 1.77777778, 4.        ])

In [51]:
c =np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [53]:
c.shape

(2, 3, 4)

In [54]:
c.ndim

3

In [56]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
ar[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [71]:
ar[-1:]

array([[7, 8, 9]])

In [72]:
ar==3


array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [73]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[5,2]])
A,B

(array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [5, 2]]))

In [78]:
sum(A)

array([1, 2])

In [82]:
np.tile(0,(8,2))

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [85]:
z = np.zeros((5,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
z + 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])